#
# This file is part of the xUSSR Trainset
# xUSSR Trainset is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, version 2.
# xUSSR Trainset is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with xUSSR Trainset. If not, see <http://www.gnu.org/licenses/>.
#

# Definition of the grfs
REPO_NAME           ?= xUSSR Trainset

# This is the filename part common to the grf file, main source file and the tar name
BASE_FILENAME       ?= xussr

# Documentation files
DOC_FILES ?= docs/readme.txt docs/license.txt docs/changelog.txt docs/readme_ru.txt docs/changelog_ru.txt

# Directory structure. If DevZone's translation service is required, don't change this
SCRIPT_DIR          ?= scripts

# Version the NewGRF is backward compatible to
# MIN_COMPATIBLE_REVISION ?= $(REPO_REVISION)

# Uncomment in order to make use of gimp scripting. See the file
# for a description of the format
# GFX_SCRIPT_LIST_FILES      := gfx/png_source_list
