name: Build and publish a release

on: push

jobs:
  build_newgrf:
    runs-on: ubuntu-latest
    name: 'Build xUSSR NewGRFs'
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Git describe
        id: describe
        uses: proudust/gh-describe@v2
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Read revision numbers
        id: revisions
        run: |
          echo "addon=$(cat versions/xussr-addon.ver)" >> $GITHUB_OUTPUT
          echo "diesel=$(cat versions/xussr-diesel.ver)" >> $GITHUB_OUTPUT
          echo "dmu=$(cat versions/xussr-dmu.ver)" >> $GITHUB_OUTPUT
          echo "electric=$(cat versions/xussr-electric.ver)" >> $GITHUB_OUTPUT
          echo "emu=$(cat versions/xussr-emu.ver)" >> $GITHUB_OUTPUT
          echo "rails=$(cat versions/xussr-rails.ver)" >> $GITHUB_OUTPUT
          echo "steam=$(cat versions/xussr-steam.ver)" >> $GITHUB_OUTPUT
          echo "wagons=$(cat versions/xussr-wagons.ver)" >> $GITHUB_OUTPUT
          echo "cars=$(cat versions/xussr-cars.ver)" >> $GITHUB_OUTPUT
          echo "subway=$(cat versions/xussr-subway.ver)" >> $GITHUB_OUTPUT
          echo "xussr=$(cat versions/xussr.ver)" >> $GITHUB_OUTPUT
      - name: Build xUSSR Addon
        id: xussr-addon
        uses: Nik-mmzd/nml-compile@v5
        with:
          nml_basename: xussr-addon
          min_compatible_revision: 1
          grf_revision: ${{ steps.revisions.outputs.addon }}
          grf_title: xUSSR Railway Set addon ${{ steps.describe.outputs.describe }}
      - name: Build xUSSR Diesels
        id: xussr-diesel
        uses: Nik-mmzd/nml-compile@v5
        with:
          nml_basename: xussr-diesel
          min_compatible_revision: 1
          grf_revision: ${{ steps.revisions.outputs.diesel }}
          grf_title: xUSSR Railway Diesels Set ${{ steps.describe.outputs.describe }}
      - name: Build xUSSR DMUs
        id: xussr-dmu
        uses: Nik-mmzd/nml-compile@v5
        with:
          nml_basename: xussr-dmu
          min_compatible_revision: 1
          grf_revision: ${{ steps.revisions.outputs.dmu }}
          grf_title: xUSSR Railway DMUs Set ${{ steps.describe.outputs.describe }}
      - name: Build xUSSR Electrics
        id: xussr-electric
        uses: Nik-mmzd/nml-compile@v5
        with:
          nml_basename: xussr-electric
          min_compatible_revision: 1
          grf_revision: ${{ steps.revisions.outputs.electric }}
          grf_title: xUSSR Railway Electrics Set ${{ steps.describe.outputs.describe }}
      - name: Build xUSSR EMUs
        id: xussr-emu
        uses: Nik-mmzd/nml-compile@v5
        with:
          nml_basename: xussr-emu
          min_compatible_revision: 1
          grf_revision: ${{ steps.revisions.outputs.emu }}
          grf_title: xUSSR Railway EMUs Set ${{ steps.describe.outputs.describe }}
      - name: Build xUSSR Rails
        id: xussr-rails
        uses: Nik-mmzd/nml-compile@v5
        with:
          nml_basename: xussr-rails
          min_compatible_revision: 1
          grf_revision: ${{ steps.revisions.outputs.rails }}
          grf_title: xUSSR Rails Set ${{ steps.describe.outputs.describe }}
      - name: Build xUSSR Steamers
        id: xussr-steam
        uses: Nik-mmzd/nml-compile@v5
        with:
          nml_basename: xussr-steam
          min_compatible_revision: 1
          grf_revision: ${{ steps.revisions.outputs.steam }}
          grf_title: xUSSR Railway Steamers Set ${{ steps.describe.outputs.describe }}
      - name: Build xUSSR Wagons
        id: xussr-wagons
        uses: Nik-mmzd/nml-compile@v5
        with:
          nml_basename: xussr-wagons
          min_compatible_revision: 1
          grf_revision: ${{ steps.revisions.outputs.wagons }}
          grf_title: xUSSR Railway Wagons Set ${{ steps.describe.outputs.describe }}
      - name: Build xUSSR Cars
        id: xussr-cars
        uses: Nik-mmzd/nml-compile@v5
        with:
          nml_basename: xussr-cars
          min_compatible_revision: 1
          grf_revision: ${{ steps.revisions.outputs.cars }}
          grf_title: xUSSR Railway Cars Set ${{ steps.describe.outputs.describe }}
      - name: Build xUSSR Subways
        id: xussr-subway
        uses: Nik-mmzd/nml-compile@v5
        with:
          nml_basename: xussr-subway
          min_compatible_revision: 1
          grf_revision: ${{ steps.revisions.outputs.subway }}
          grf_title: xUSSR Subways Set ${{ steps.describe.outputs.describe }}
      - name: Build xUSSR
        id: xussr
        uses: Nik-mmzd/nml-compile@v5
        with:
          nml_basename: xussr
          min_compatible_revision: 1
          grf_revision: ${{ steps.revisions.outputs.xussr }}
          grf_title: xUSSR Railway Set ${{ steps.describe.outputs.describe }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: xUSSR GRFs
          path: build/*.grf
          if-no-files-found: error
      - name: Publish nightly release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly/${{ steps.extract_branch.outputs.branch }}
          name: ${{ steps.extract_branch.outputs.branch }}-nightly
          body: Nighly build for branch `${{ steps.extract_branch.outputs.branch }}` (commit ${{ github.sha }})
          files: build/*.grf
          prerelease: true
      - name: Publish release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'build/*.grf'
